### ISSUE TITLE
DD_EXTENSION  warn

### ISSUE THREAD

**Issue by pedrolourencoribeiro** [DataDog/datadog-lambda-extension#140] opened 2023-04-12 14:10 UTC
Hi

I'm currently monitoring some lambdas with DD and I'm getting a lot of warn messages from the DD_EXTENSION layer.

`2023-04-12 10:38:54 UTC | DD_EXTENSION | WARN | Failed to identify cgroups version due to err: unable to detect cgroup version from detected mount points: map[]. APM data may be missing containerIDs.`

Previously we had this warning but since I've updated to the latest version it no longer appears
`DD_EXTENSION | WARN | Error loading config: open /var/task/datadog.yaml: no such file or directory`

I'm using the latest versions of the layers and running node16

```
"arn:aws:lambda:eu-west-1:464622532012:layer:Datadog-Node16-x:90"
"arn:aws:lambda:eu-west-1:464622532012:layer:Datadog-Extension:41",
```

and these are the variables that I'm passing to the lambda

```
DD_ENV | dev
DD_FLUSH_TO_LOG | false
DD_LAMBDA_HANDLER | index.handler
DD_LOG_LEVEL | warn
DD_LOGS_CONFIG_PROCESSING_RULES | [{"type": "exclude_at_match", "name": "exclude_start_and_end_logs", "pattern": "(START\|END\|REPORT) RequestId"}]
DD_MERGE_XRAY_TRACES | false
DD_SERVICE | my-analyses
DD_SITE | datadoghq.eu
DD_TRACE_ENABLED | true
```

Do you guys know why this could be happening or a way to stop logging it since its costly and not really relevant for us
Thanks in advance

**Comment by t0mmili** [comment] 2023-04-17 11:23
Same here.

Additionally I'm receiving these warnings:
```
DD_EXTENSION \| WARN \| Unknown environment variable: DD_API_KEY_SECRET_ARN
DD_EXTENSION \| WARN \| Unknown environment variable: DD_VERSION
```

Of course both env vars are set and recognized by DD.

**Comment by purple4reina** [comment] 2023-04-28 18:33
@pedrolourencoribeiro and @t0mmili both PRs related to this issue have been merged. They will be included in the next release of the Datadog Lambda Extension.

**Closed by purple4reina** 2023-04-28 18:33 UTC

**Comment by mbrmchll** [comment] 2023-06-08 21:09
> @pedrolourencoribeiro and @t0mmili both PRs related to this issue have been merged. They will be included in the next release of the Datadog Lambda Extension.

Has this been released? I see that the issue is closed and you mentioned it was merged and would be released in the next release, but we are still seeing the "missing containerIDs" warning in our Lambda function using v43.

2023-06-08 20:46:15 UTC | DD_EXTENSION | WARN | Failed to identify cgroups version due to err: unable to detect cgroup version from detected mount points: map[]. APM data may be missing containerIDs.
