### ISSUE TITLE
Filtering Ignored on Tracing 

### ISSUE THREAD

**Issue by Ballymultani** [DataDog/datadog-lambda-extension#78] opened 2022-08-30 08:48 UTC
It seems that we try to filter out spans using the env variable DD_TRACE_DISABLED_PLUGINS=dns, this does not seem to work. After further investigation, it seems that the port which statsd uses (8125) has been entirely missed as part of filtering checks. Original work was done here:  https://github.com/DataDog/datadog-agent/pull/11687.

**Comment by jcstorms1** [comment] 2022-09-01 14:50
@Ballymultani thanks for bringing this to our attention. This should go out in the next release.

**Comment by Ballymultani** [comment] 2022-09-01 14:51
Thanks @jcstorms1 when will the next release be available?

**Comment by jcstorms1** [comment] 2022-09-09 15:49
@Ballymultani Sorry I missed this. We are currently testing the next release and once it is out I will update you.

**Comment by jcstorms1** [comment] 2022-09-16 17:06
@Ballymultani Just following up. The release is available as [v29](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v29)

**Comment by Ballymultani** [comment] 2022-09-16 17:20
Thank you @jcstorms1

**Comment by DarcyRaynerDD** [comment] 2022-10-11 14:07
@Ballymultani You mentioned on slack you were still seeing this issue. Could you share any other details about the spans you are seeing?

**Comment by Ballymultani** [comment] 2022-10-11 14:41
Ok so when I add the span, I'm not seeing those dns.lookup being from the spans (APM). How is this expected to work?

**Comment by Ballymultani** [comment] 2022-10-11 14:42
Like, when I add this, what should happen?

![image](https://user-images.githubusercontent.com/35222777/195122529-e7dc5e8f-6434-4d36-8a5b-5a20d2d87cab.png)

**Comment by Ballymultani** [comment] 2022-10-11 14:54
More info: these are the spans I'm currently seeing that should be filtered out:
![image](https://user-images.githubusercontent.com/35222777/195125514-3705746e-b8f3-4d7e-bd18-0a8cdb434606.png)

**Comment by jcstorms1** [comment] 2022-10-12 19:30
Hey @Ballymultani thanks for bringing this to our attention. I was able to reproduce this on our end and I've created a card in our backlog to address the issue. We will update you with more information when it is available.

**Comment by Ballymultani** [comment] 2022-10-12 19:41
Ok much appreciated thank you.

**Comment by Kiskaa** [comment] 2022-11-22 09:31
Hi is there any update on this @jcstorms1  ?

**Comment by duncanista** [comment] 2024-01-10 17:57
Hey @Ballymultani and @Kiskaa, this seemed to have been released a long time ago.

If I'm mistaken and something else needs to be done here, please feel free to re-open this issue.

I'm closing since this seems to have been released since the [v40](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v40).

**Closed by duncanista** 2024-01-10 17:57 UTC
